// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package realprogress.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import realprogress.helpers.RealProgressCore;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Will return the progress of this object and session, call this in a microflow timer or the RealProgress widget.
 */
public class GetProgress extends CustomJavaAction<Long>
{
	private IMendixObject anyObject;

	public GetProgress(IContext context, IMendixObject anyObject)
	{
		super(context);
		this.anyObject = anyObject;
	}

	@Override
	public Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Long p = RealProgressCore.getInstance().getProgress(anyObject, this.getContext().getSession());
		Core.getLogger("Progress").trace("getProgress " + p);
		//String mendixId = Long.toString(anyObject.getId().toLong()) + "-" + this.getContext().getSession().getId();
		return p;	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetProgress";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
