// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package realprogress.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import realprogress.helpers.RealProgressCore;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Will return the message of this object and session
 */
public class GetProgressMessage extends CustomJavaAction<String>
{
	private IMendixObject anyObject;

	public GetProgressMessage(IContext context, IMendixObject anyObject)
	{
		super(context);
		this.anyObject = anyObject;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String message = RealProgressCore.getInstance().getProgressMessage(anyObject, this.getContext().getSession());
		Core.getLogger("Progress").trace("getProgress message " + message);
		return message;	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetProgressMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
