// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package realprogress.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Set the max value of this progress. Default value is 100. Set this to for example count of objects you process. Can be called multiple times.
 */
public class SetProgressMax extends CustomJavaAction<Boolean>
{
	private IMendixObject anyObject;
	private Long max;

	public SetProgressMax(IContext context, IMendixObject anyObject, Long max)
	{
		super(context);
		this.anyObject = anyObject;
		this.max = max;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetProgressMax";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
