// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package realprogress.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import realprogress.helpers.RealProgressCore;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Set the progress from a microflow.
 * Message=empty won't overwrite previous message.
 */
public class SetProgress extends CustomJavaAction<Boolean>
{
	private IMendixObject anyObject;
	private Long progress;
	private String message;

	public SetProgress(IContext context, IMendixObject anyObject, Long progress, String message)
	{
		super(context);
		this.anyObject = anyObject;
		this.progress = progress;
		this.message = message;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.getLogger("Progress").trace("setProgress " + progress);
		RealProgressCore.getInstance().setProgress(anyObject, this.getContext().getSession(), progress.intValue());	
		if (message != null) {
			RealProgressCore.getInstance().setMessage(anyObject, this.getContext().getSession(), message);	
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetProgress";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
